---
name: Test-HexString
version: 0.01
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: test binary strings with hex dump diagnostics
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Builder: 0
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
provides:
  Test::HexString:
    file: lib/Test/HexString.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
